spring:
  main:
    banner-mode: off
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15

my.service:
  enabled: false
  remote-address: 192.168.0.1
  security:
    username: soohoonlee
    password: 821126
    roles:
      - ADMIN
      - USER
    attrs:
      hasWriteAuthority: false
      hasReadAuthority: true
      hasDeleteAuthority: false
