spring:
  profiles:
    active:
      - local
    include:
      - db
      - my-service
      - site
    group:
      local: "site-local,db-local"
      dev: "site-dev"
  main:
    banner-mode: off
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15
#  mvc:
#    static-path-pattern: /resources/**
  messages:
    basename: classpath:/messages
#logging:
#  file:
#    name: app.log
#    path: logs
#  level:
#    '[org.springframework.web]': debug